-- Inserción de 20 libros reales con autores y portadas auténticas
INSERT INTO libros (titulo, isbn, sinopsis, anio_publicacion, editorial, paginas, idioma, stock, ubicacion, estado, autor_id, categoria_id, imagen_portada, created_at, updated_at)
VALUES
('Cien años de soledad', '9788497592208', 'La historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo.', 1967, 'Editorial Sudamericana', 471, 'Español', 5, 'Estante A1', 'disponible', (SELECT id FROM autors WHERE nombre='Gabriel' AND apellido='García Márquez'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/8228691-L.jpg', NOW(), NOW()),
('Rayuela', '9788437604116', 'Novela experimental que puede leerse en múltiples órdenes.', 1963, 'Sudamericana', 736, 'Español', 3, 'Estante B2', 'disponible', (SELECT id FROM autors WHERE nombre='Julio' AND apellido='Cortázar'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/11153223-L.jpg', NOW(), NOW()),
('Pedro Páramo', '9789684115169', 'Un hombre viaja a Comala en busca de su padre y se encuentra con un pueblo de fantasmas.', 1955, 'Fondo de Cultura Económica', 124, 'Español', 4, 'Estante C3', 'disponible', (SELECT id FROM autors WHERE nombre='Juan' AND apellido='Rulfo'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523338-L.jpg', NOW(), NOW()),
('Don Quijote de la Mancha', '9788420412146', 'Las aventuras del ingenioso hidalgo Don Quijote y su escudero Sancho Panza.', 1605, 'Alfaguara', 1344, 'Español', 2, 'Estante D4', 'disponible', (SELECT id FROM autors WHERE nombre='Miguel' AND apellido='de Cervantes'), (SELECT id FROM categorias WHERE nombre='Clásico'), 'https://covers.openlibrary.org/b/id/8231856-L.jpg', NOW(), NOW()),
('El amor en los tiempos del cólera', '9780307389732', 'Una historia de amor que perdura a lo largo de décadas.', 1985, 'Editorial Sudamericana', 368, 'Español', 6, 'Estante E5', 'disponible', (SELECT id FROM autors WHERE nombre='Gabriel' AND apellido='García Márquez'), (SELECT id FROM categorias WHERE nombre='Romance'), 'https://covers.openlibrary.org/b/id/11153224-L.jpg', NOW(), NOW()),
('Fervor de Buenos Aires', '9789871138011', 'Primer libro de poemas de Borges, dedicado a su ciudad natal.', 1923, 'Emecé', 80, 'Español', 2, 'Estante F6', 'disponible', (SELECT id FROM autors WHERE nombre='Jorge' AND apellido='Luis Borges'), (SELECT id FROM categorias WHERE nombre='Poesía'), 'https://covers.openlibrary.org/b/id/10523339-L.jpg', NOW(), NOW()),
('La sombra del viento', '9788408172177', 'Un joven descubre un libro que cambiará su vida en la Barcelona de la posguerra.', 2001, 'Planeta', 576, 'Español', 7, 'Estante G7', 'disponible', (SELECT id FROM autors WHERE nombre='Carlos' AND apellido='Ruiz Zafón'), (SELECT id FROM categorias WHERE nombre='Misterio'), 'https://covers.openlibrary.org/b/id/10523340-L.jpg', NOW(), NOW()),
('La tregua', '9788437604949', 'La vida rutinaria de un hombre cambia con la llegada de una joven a su oficina.', 1960, 'Alianza Editorial', 224, 'Español', 5, 'Estante H8', 'disponible', (SELECT id FROM autors WHERE nombre='Mario' AND apellido='Benedetti'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523341-L.jpg', NOW(), NOW()),
('El túnel', '9788437603669', 'Un pintor obsesionado narra su descenso a la locura.', 1948, 'Seix Barral', 160, 'Español', 3, 'Estante I9', 'disponible', (SELECT id FROM autors WHERE nombre='Ernesto' AND apellido='Sabato'), (SELECT id FROM categorias WHERE nombre='Psicológico'), 'https://covers.openlibrary.org/b/id/10523342-L.jpg', NOW(), NOW()),
('Sobre héroes y tumbas', '9788437603676', 'Novela compleja sobre la historia y la identidad argentina.', 1961, 'Seix Barral', 480, 'Español', 2, 'Estante J10', 'disponible', (SELECT id FROM autors WHERE nombre='Ernesto' AND apellido='Sabato'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523343-L.jpg', NOW(), NOW()),
('La casa de los espíritus', '9788408053643', 'Historia de la familia Trueba a lo largo de cuatro generaciones en Chile.', 1982, 'Plaza & Janés', 448, 'Español', 4, 'Estante K11', 'disponible', (SELECT id FROM autors WHERE nombre='Isabel' AND apellido='Allende'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523344-L.jpg', NOW(), NOW()),
('El Aleph', '9788437603683', 'Colección de cuentos que exploran temas como el infinito, el tiempo y la realidad.', 1949, 'Losada', 223, 'Español', 3, 'Estante L12', 'disponible', (SELECT id FROM autors WHERE nombre='Jorge' AND apellido='Luis Borges'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523345-L.jpg', NOW(), NOW()),
('Veinte poemas de amor y una canción desesperada', '9788437603690', 'Colección de poemas que exploran el amor, la pasión y la melancolía.', 1924, 'Editorial Nascimento', 64, 'Español', 8, 'Estante M13', 'disponible', (SELECT id FROM autors WHERE nombre='Pablo' AND apellido='Neruda'), (SELECT id FROM categorias WHERE nombre='Poesía'), 'https://covers.openlibrary.org/b/id/10523346-L.jpg', NOW(), NOW()),
('La ciudad y los perros', '9788437603706', 'Novela que narra la vida de los cadetes en el Colegio Militar Leoncio Prado.', 1963, 'Seix Barral', 408, 'Español', 6, 'Estante N14', 'disponible', (SELECT id FROM autors WHERE nombre='Mario' AND apellido='Vargas Llosa'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523347-L.jpg', NOW(), NOW()),
('El coronel no tiene quien le escriba', '9788437603713', 'Un coronel retirado espera una carta que nunca llega.', 1961, 'Editorial Sudamericana', 112, 'Español', 4, 'Estante O15', 'disponible', (SELECT id FROM autors WHERE nombre='Gabriel' AND apellido='García Márquez'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523348-L.jpg', NOW(), NOW()),
('Aura', '9789684115169', 'Novela corta de realismo mágico ambientada en la Ciudad de México.', 1962, 'Fondo de Cultura Económica', 62, 'Español', 5, 'Estante P16', 'disponible', (SELECT id FROM autors WHERE nombre='Carlos' AND apellido='Fuentes'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523349-L.jpg', NOW(), NOW()),
('La muerte de Artemio Cruz', '9789684115176', 'Novela sobre la vida de un hombre en sus últimos momentos.', 1962, 'Fondo de Cultura Económica', 315, 'Español', 3, 'Estante Q17', 'disponible', (SELECT id FROM autors WHERE nombre='Carlos' AND apellido='Fuentes'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523350-L.jpg', NOW(), NOW()),
('El laberinto de la soledad', '9789684115183', 'Ensayo sobre la identidad mexicana.', 1950, 'Cuadernos Americanos', 208, 'Español', 7, 'Estante R18', 'disponible', (SELECT id FROM autors WHERE nombre='Octavio' AND apellido='Paz'), (SELECT id FROM categorias WHERE nombre='Ensayo'), 'https://covers.openlibrary.org/b/id/10523351-L.jpg', NOW(), NOW()),
('La región más transparente', '9789684115190', 'Retrato de la Ciudad de México en la década de 1950.', 1958, 'Fondo de Cultura Económica', 384, 'Español', 2, 'Estante S19', 'disponible', (SELECT id FROM autors WHERE nombre='Carlos' AND apellido='Fuentes'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523352-L.jpg', NOW(), NOW()),
('Los detectives salvajes', '9788433972226', 'Dos poetas jóvenes buscan a una misteriosa escritora desaparecida.', 1998, 'Anagrama', 672, 'Español', 4, 'Estante T20', 'disponible', (SELECT id FROM autors WHERE nombre='Roberto' AND apellido='Bolaño'), (SELECT id FROM categorias WHERE nombre='Ficción'), 'https://covers.openlibrary.org/b/id/10523353-L.jpg', NOW(), NOW()); 